.TH "FOTOWALL" "1"
.SH "NAME"
fotowall \- wallpaper generator for high resolution composition.
.SH "SYNOPSIS"
\fBfotowall\fR [project] [images]
.SH "DESCRIPTION"
This manual page documents briefly the \fBfotowall\fR binary.
\fBfotowall\fR is a wallpaper generator rendering some of your favorite
pictures in a nice and smooth high resolution composition.
.SH "BINARY PARAMETERS"
.TP
\fB-clearconfig\fP
Start Fotowall with the factory settings. Can be used to reset a broken
configuration.
\fB-novideo\fP
Load Fotowall without checking for video device.
.SH "AUTHOR"
This manual page was written by Patrick Matth\[:a]i <patrick.matthaei@web.de>
for \fBfotowall\fR.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
