#############################################################################
# Makefile for building: fotowall
# Generated by qmake (2.01a) (Qt 4.4.3) on: sam. nov. 22 09:54:55 2008
# Project:  fotowall.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile fotowall.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ColorPickerItem.cpp \
		FotoWall.cpp \
		FWFoto.cpp \
		FWScene.cpp \
		FWPictureInfo.cpp \
		BackgroundChooser.cpp \
		main.cpp \
		CPixmap.cpp moc_ColorPickerItem.cpp \
		moc_FotoWall.cpp \
		moc_FWFoto.cpp \
		moc_FWScene.cpp \
		moc_BackgroundChooser.cpp \
		moc_SizeDialog.cpp \
		qrc_fotowall.cpp
OBJECTS       = ColorPickerItem.o \
		FotoWall.o \
		FWFoto.o \
		FWScene.o \
		FWPictureInfo.o \
		BackgroundChooser.o \
		main.o \
		CPixmap.o \
		moc_ColorPickerItem.o \
		moc_FotoWall.o \
		moc_FWFoto.o \
		moc_FWScene.o \
		moc_BackgroundChooser.o \
		moc_SizeDialog.o \
		qrc_fotowall.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		fotowall.pro
QMAKE_TARGET  = fotowall
DESTDIR       = 
TARGET        = fotowall

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_FotoWall.h ui_Aide.h ui_BackgroundChooser.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fotowall.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile fotowall.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile fotowall.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fotowall1.0.0 || $(MKDIR) .tmp/fotowall1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fotowall1.0.0/ && $(COPY_FILE) --parents ColorPickerItem.h FotoWall.h FWFoto.h FWScene.h FWPictureInfo.h opencvtoqt.h BackgroundChooser.h SizeDialog.h CPixmap.h .tmp/fotowall1.0.0/ && $(COPY_FILE) --parents fotowall.qrc .tmp/fotowall1.0.0/ && $(COPY_FILE) --parents ColorPickerItem.cpp FotoWall.cpp FWFoto.cpp FWScene.cpp FWPictureInfo.cpp BackgroundChooser.cpp main.cpp CPixmap.cpp .tmp/fotowall1.0.0/ && $(COPY_FILE) --parents FotoWall.ui Aide.ui BackgroundChooser.ui .tmp/fotowall1.0.0/ && $(COPY_FILE) --parents fotowall_fr.ts .tmp/fotowall1.0.0/ && (cd `dirname .tmp/fotowall1.0.0` && $(TAR) fotowall1.0.0.tar fotowall1.0.0 && $(COMPRESS) fotowall1.0.0.tar) && $(MOVE) `dirname .tmp/fotowall1.0.0`/fotowall1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fotowall1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ColorPickerItem.cpp moc_FotoWall.cpp moc_FWFoto.cpp moc_FWScene.cpp moc_BackgroundChooser.cpp moc_SizeDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ColorPickerItem.cpp moc_FotoWall.cpp moc_FWFoto.cpp moc_FWScene.cpp moc_BackgroundChooser.cpp moc_SizeDialog.cpp
moc_ColorPickerItem.cpp: ColorPickerItem.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ColorPickerItem.h -o moc_ColorPickerItem.cpp

moc_FotoWall.cpp: ui_FotoWall.h \
		FotoWall.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FotoWall.h -o moc_FotoWall.cpp

moc_FWFoto.cpp: define.h \
		FWPictureInfo.h \
		CPixmap.h \
		FWFoto.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FWFoto.h -o moc_FWFoto.cpp

moc_FWScene.cpp: FWScene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) FWScene.h -o moc_FWScene.cpp

moc_BackgroundChooser.cpp: ui_BackgroundChooser.h \
		BackgroundChooser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) BackgroundChooser.h -o moc_BackgroundChooser.cpp

moc_SizeDialog.cpp: SizeDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SizeDialog.h -o moc_SizeDialog.cpp

compiler_rcc_make_all: qrc_fotowall.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fotowall.cpp
qrc_fotowall.cpp: fotowall.qrc \
		data/icon.png
	/usr/bin/rcc -name fotowall fotowall.qrc -o qrc_fotowall.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_FotoWall.h ui_Aide.h ui_BackgroundChooser.h
compiler_uic_clean:
	-$(DEL_FILE) ui_FotoWall.h ui_Aide.h ui_BackgroundChooser.h
ui_FotoWall.h: FotoWall.ui
	/usr/bin/uic-qt4 FotoWall.ui -o ui_FotoWall.h

ui_Aide.h: Aide.ui
	/usr/bin/uic-qt4 Aide.ui -o ui_Aide.h

ui_BackgroundChooser.h: BackgroundChooser.ui
	/usr/bin/uic-qt4 BackgroundChooser.ui -o ui_BackgroundChooser.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

ColorPickerItem.o: ColorPickerItem.cpp ColorPickerItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColorPickerItem.o ColorPickerItem.cpp

FotoWall.o: FotoWall.cpp FotoWall.h \
		ui_FotoWall.h \
		FWScene.h \
		ui_Aide.h \
		SizeDialog.h \
		BackgroundChooser.h \
		ui_BackgroundChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FotoWall.o FotoWall.cpp

FWFoto.o: FWFoto.cpp FWFoto.h \
		define.h \
		FWPictureInfo.h \
		CPixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FWFoto.o FWFoto.cpp

FWScene.o: FWScene.cpp FWScene.h \
		FWFoto.h \
		define.h \
		FWPictureInfo.h \
		CPixmap.h \
		ColorPickerItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FWScene.o FWScene.cpp

FWPictureInfo.o: FWPictureInfo.cpp FWPictureInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FWPictureInfo.o FWPictureInfo.cpp

BackgroundChooser.o: BackgroundChooser.cpp BackgroundChooser.h \
		ui_BackgroundChooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BackgroundChooser.o BackgroundChooser.cpp

main.o: main.cpp FotoWall.h \
		ui_FotoWall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

CPixmap.o: CPixmap.cpp CPixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPixmap.o CPixmap.cpp

moc_ColorPickerItem.o: moc_ColorPickerItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ColorPickerItem.o moc_ColorPickerItem.cpp

moc_FotoWall.o: moc_FotoWall.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FotoWall.o moc_FotoWall.cpp

moc_FWFoto.o: moc_FWFoto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FWFoto.o moc_FWFoto.cpp

moc_FWScene.o: moc_FWScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FWScene.o moc_FWScene.cpp

moc_BackgroundChooser.o: moc_BackgroundChooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_BackgroundChooser.o moc_BackgroundChooser.cpp

moc_SizeDialog.o: moc_SizeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SizeDialog.o moc_SizeDialog.cpp

qrc_fotowall.o: qrc_fotowall.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fotowall.o qrc_fotowall.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

