name: CI of fotowall

on:
  push:
    paths-ignore: &paths-ignore
      # Changes to those files don't mandate running CI
      - ".github/workflows/package.yml"
      - ".github/workflows/sources/*"
      - ".github/workflows/build-others.yml"
      - ".github/workflows/docker/*"
      - "debian/**"
    branches:
      - 'master'
  pull_request:
    paths-ignore: *paths-ignore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-26.04]
        build-type: [RelWithDebInfo, Release]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Install dependencies (Qt5)
      if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-24.04'
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: qtbase5-dev libqt5svg5-dev libqt5webkit5-dev qttools5-dev-tools
    - name: Install dependencies (Qt6)
      if: matrix.os == 'ubuntu-26.04'
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: qt6-base-dev qt6-svg-dev qt6-tools-dev-tools
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
